#!/bin/bash
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
#Decrypted By YADDY D PHREAKER
clear
red='\e[1;31m'
green='\e[0;32m'
yell='\e[1;33m'
tyblue='\e[1;36m'
NC='\e[0m'
purple() { echo -e "\\033[35;1m${*}\\033[0m"; }
tyblue() { echo -e "\\033[36;1m${*}\\033[0m"; }
yellow() { echo -e "\\033[33;1m${*}\\033[0m"; }
green() { echo -e "\\033[32;1m${*}\\033[0m"; }
red() { echo -e "\\033[31;1m${*}\\033[0m"; }
curl ipinfo.io/org | cut -d ' ' -f 2-10 > /root/.myisp
#curl ipinfo.io/org > /root/.myisp
curl ipinfo.io/city > /root/.mycity
curl ipinfo.io/ip > /root/.myip
curl ipinfo.io/org > /root/.isp
curl ipinfo.io/city > /root/.city
curl ifconfig.me > /root/.ip
curl ipinfo.io/region > /root/.region
function alatdebian(){
echo "ini vps debian"
OS=$ID # debian or ubuntu
#apt install -y nginx certbot
sleep 3s
sudo apt update -y
sudo apt upgrade -y
sudo apt dist-upgrade -y
update-grub
sudo apt-get remove --purge ufw firewalld -y
sudo apt-get remove --purge exim4 -y
apt install sysstat -y
apt -y install shc
apt install figlet -y
apt install ruby nload gawk htop bc iftop -y
apt install build-essential zlib1g-dev libpcre3 libpcre3-dev -y
apt install libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential gcc make cmake -y
apt install xz-utils apt-transport-https gnupg gnupg2 gnupg1 dnsutils lsb-release -y
apt install socat cron bash-completion ntpdate -y
apt install software-properties-common -y
apt install certbot python python2 python3 python3-dnslib python3-pip -y
apt install iptables iptables-persistent -y
apt install libncurses5-dev libncursesw5-dev -y
apt install -y dos2unix debconf-utils dnsutils
apt install -y whois golang
apt install -y sudo net-tools gnutls-bin neofetch vnstat uuid
apt install -y pwgen php jq git curl wget
apt install -y mlocate dh-make libaudit-dev build-essential
apt install -y bzip2 gzip coreutils screen unzip
sudo apt install -y screen curl jq bzip2 gzip coreutils rsyslog iftop \
htop zip unzip net-tools sed gnupg gnupg1 \
bc sudo apt-transport-https build-essential dirmngr libxml-parser-perl neofetch screenfetch git lsof \
openssl openvpn easy-rsa fail2ban tmux \
stunnel4 vnstat squid3 \
dropbear  libsqlite3-dev \
socat cron bash-completion ntpdate xz-utils sudo apt-transport-https \
gnupg2 dnsutils lsb-release chrony
#curl -sSL https://deb.nodesource.com/setup_16.x | bash -
sudo apt-get install nodejs -y
/etc/init.d/vnstat restart
wget -q https://humdi.net/vnstat/vnstat-2.6.tar.gz
tar zxvf vnstat-2.6.tar.gz
cd vnstat-2.6
./configure --prefix=/usr --sysconfdir=/etc >/dev/null 2>&1 && make >/dev/null 2>&1 && make install >/dev/null 2>&1
cd
vnstat -u -i $NET
sed -i 's/Interface "'""eth0""'"/Interface "'""$NET""'"/g' /etc/vnstat.conf
chown vnstat:vnstat /var/lib/vnstat -R
systemctl enable vnstat
/etc/init.d/vnstat restart
rm -f /root/vnstat-2.6.tar.gz >/dev/null 2>&1
rm -rf /root/vnstat-2.6 >/dev/null 2>&1
sudo apt install -y libnss3-dev libnspr4-dev pkg-config libpam0g-dev libcap-ng-dev libcap-ng-utils libselinux1-dev libcurl4-nss-dev flex bison make libnss3-tools libevent-dev xl2tpd pptpd
clear
}
function alatubuntu() {
echo "ini vps Ubuntu"
OS=$ID # debian or ubuntu
#apt-get install -y nginx certbot
sleep 3s
apt-get update -y
apt-get upgrade -y
apt-get dist-upgrade -y
update-grub
apt-get install sysstat -y
apt-get -y install shc
apt-get install figlet -y
apt-get install ruby nload gawk htop bc iftop -y
apt-get install build-essential zlib1g-dev libpcre3 libpcre3-dev -y
apt-get install libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential gcc make cmake -y
apt-get install xz-utils apt-transport-https gnupg gnupg2 gnupg1 dnsutils lsb-release -y
apt-get install socat cron bash-completion ntpdate -y
apt-get install software-properties-common -y
apt-get install certbot python python2 python3 python3-dnslib python3-pip -y
apt-get install iptables iptables-persistent -y
apt-get install libncurses5-dev libncursesw5-dev -y
apt-get install -y dos2unix debconf-utils dnsutils
apt-get install -y whois golang
apt-get install -y sudo net-tools gnutls-bin neofetch vnstat uuid
apt-get install -y pwgen php jq git curl wget
apt-get install -y mlocate dh-make libaudit-dev build-essential
apt-get install -y bzip2 gzip coreutils screen unzip
sudo apt-get install -y screen curl jq bzip2 gzip coreutils rsyslog iftop \
htop zip unzip net-tools sed gnupg gnupg1 \
bc sudo apt-transport-https build-essential dirmngr libxml-parser-perl neofetch screenfetch git lsof \
openssl openvpn easy-rsa fail2ban tmux \
stunnel4 vnstat squid3 \
dropbear  libsqlite3-dev \
socat cron bash-completion ntpdate xz-utils sudo apt-transport-https \
gnupg2 dnsutils lsb-release chrony
#curl -sSL https://deb.nodesource.com/setup_16.x | bash - 
sudo apt-get install nodejs -y
/etc/init.d/vnstat restart
wget -q https://humdi.net/vnstat/vnstat-2.6.tar.gz
tar zxvf vnstat-2.6.tar.gz
cd vnstat-2.6
./configure --prefix=/usr --sysconfdir=/etc >/dev/null 2>&1 && make >/dev/null 2>&1 && make install >/dev/null 2>&1
cd
vnstat -u -i $NET
sed -i 's/Interface "'""eth0""'"/Interface "'""$NET""'"/g' /etc/vnstat.conf
chown vnstat:vnstat /var/lib/vnstat -R
systemctl enable vnstat
/etc/init.d/vnstat restart
rm -f /root/vnstat-2.6.tar.gz >/dev/null 2>&1
rm -rf /root/vnstat-2.6 >/dev/null 2>&1
sudo apt-get install -y libnss3-dev libnspr4-dev pkg-config libpam0g-dev libcap-ng-dev libcap-ng-utils libselinux1-dev libcurl4-nss-dev flex bison make libnss3-tools libevent-dev xl2tpd pptpd
clear
}
function SystemOperasi(){
source /etc/os-release
    if [ -f "/usr/bin/apt-get" ];then
            isDebian=`cat /etc/issue|grep Debian`
            if [ "$isDebian" != "" ];then
                    alatdebian
            else
                    alatubuntu
            fi
    else
        echo "ini vps Centos"
        OS=centos
        #yum install -y nginx certbot
        echo "ubah manual apt menjadi yum , contoh apt install squid menjadi yum install squid"
        echo "atau chat saya di telegram kalau kamu ga paham"
        echo "contact person t.me/Crystalllz"
        sleep 3s
        exit
    fi
}
SystemOperasi
apt install python3-pip -y
pip3 install telegram-send
clear
