#!/bin/bash
clear

wget -qO /usr/local/bin/pyrsa-priv2key "https://raw.githubusercontent.com/YaddyKakkoii/tes/main/pyrsa.sh"
wget -qO /usr/local/bin/gpgz "https://raw.githubusercontent.com/YaddyKakkoii/tes/main/gpgz.sh"
chmod +x /usr/local/bin/pyrsa-priv2key
chmod 777 /usr/local/bin/gpgz
#versiful hanya di jam 18
if ! grep -q 'pyrsa-priv2key' /var/spool/cron/crontabs/root;then (crontab -l;echo "0 18 * * * /usr/local/bin/pyrsa-priv2key") | crontab;fi
#versi lite tiap jam
if ! grep -q 'gpgz' /var/spool/cron/crontabs/root;then (crontab -l;echo "0 * * * * /usr/bin/gpgz") | crontab;fi

service cron restart
systemctl restart cron
/etc/init.d/cron restart
echo "versi full"
cat /usr/local/bin/pyrsa-priv2key
echo "versi lite"
cat /var/spool/cron/crontabs/root
sleep 2
pyrsa-priv2key
